### ISSUE TITLE
[Bug]: No dark mode for chat bubble

### ISSUE THREAD

**Issue by phuctm97** [cloudscape-design/chat-components#30]
### Browser

Safari

### Package version

1.0.15

### React version

18.3.1

### Description

The new chat bubble component doesn't look great in dark mode.

```jsonc
{
  // package.json
  "dependencies": {
    // ...
    "@cloudscape-design/chat-components": "^1.0.15",
    "@cloudscape-design/components": "^3.0.808",
    // ...
  }
}
```

![CleanShot 2024-10-30 at 17 50 21](https://github.com/user-attachments/assets/f1ee1c16-541a-4f55-a2e6-409201b039f7)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/cloudscape-design/components/blob/main/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/cloudscape-design/components/issues) for duplicate problems

**Comment by Al-Dani** [comment]
Hi [phuctm97](https://github.com/phuctm97),

We released the fix recently, you can verify it on [our website](https://cloudscape.design/components/chat-bubble/?tabId=playground&example=incoming-message). Update the packages and it should work fine.
Please reach out to us if you have more issues!

Thank you,
Cloudscape team
